name: "APT repository management action"
description: "Maintain an APT repository by adding .deb files to an OpenStack compatible object storage instance"
author: "Steven Leadbeater <info@ledsysconsultancy.com>"
inputs:
  storage_container_url:
    description: 'URL of OpenStack compatible Object Storage container'
    required: true
  open_stack_authorisation_url:
    description: 'URL of OpenStack authorisation end point'
    required: true
  open_stack_project_id:
    description: 'OpenStack project ID with which the target Object Storage container is associated'
    required: true
  swift_client_username:
    description: 'OpenStack / Swift client username for uploads'
    required: true
  swift_client_password:
    description: 'OpenStack / Swift client password for uploads'
    required: true
  swift_region_name:
    description: 'OpenStack / Swift client region name for target Object Storage container'
    required: true
  swift_container_name:
    description: 'OpenStack / Swift client name for target Object Storage container'
    required: true
  private_key:
    description: 'GPG Private key in ascii armor format for signing packages'
    required: true
  private_key_email:
    description: 'GPG Private key email address'
    required: true
  private_key_passphrase:
    description: 'GPG Private key passphrase'
    required: true
  public_key:
    description: 'GPG Public key file name, stored in ascii armor for verifying signing packages - This may well exceed the size limit for secrets!!!'
    required: true
  list_file_name:
    description: 'Name of the .list file users will download and add to their local machines when consuming your PPA'
    required: true
  execution_path:
    description: 'Sub directory in which to execute the action'
    required: true
    default: '.'

branding:
  icon: "anchor"
  color: "blue"

runs:
  using: docker
  image: docker://albeego/apt-repository-action:0.0.1