name: "APT repository management action"
description: "Maintain an APT repository by adding .deb files to an OpenStack compatible object storage instance"
author: "Steven Leadbeater <info@ledsysconsultancy.com>"
inputs:
  storageContainerUrl:
    description: 'URL of OpenStack compatible Object Storage container'
    required: true
  openStackAuthorisationUrl:
    description: 'URL of OpenStack authorisation end point'
    required: true
  openStackProjectId:
    description: 'OpenStack project ID with which the target Object Storage container is associated'
    required: true
  swiftClientUsername:
    description: 'OpenStack / Swift client username for uploads'
    required: true
  swiftClientPassword:
    description: 'OpenStack / Swift client password for uploads'
    required: true
  swiftRegionName:
    description: 'OpenStack / Swift client region name for target Object Storage container'
    required: true
  swiftContainerName:
    description: 'OpenStack / Swift client name for target Object Storage container'
    required: true
  privateKey:
    description: 'GPG Private key in ascii armor format for signing packages'
    required: true
  privateKeyEmail:
    description: 'GPG Private key email address'
    required: true
  privateKeyPassphrase:
    description: 'GPG Private key passphrase'
    required: true
  publicKey:
    description: 'GPG Public key in ascii armor for verifying signing packages'
    required: true
  listFileName:
    description: 'Name of the .list file users will download and add to their local machines when consuming your PPA'
    required: true

branding:
  icon: "anchor"
  color: "blue"

runs:
  using: docker
  image: docker://albeego/apt-repository-action:0.0.1