name: "APT repository management action"
description: "Maintain an APT repository by adding .deb files to an OpenStack compatible object storage instance"
author: "Steven Leadbeater <info@ledsysconsultancy.com>"
inputs:
  storage-container-url:
    description: 'URL of OpenStack compatible Object Storage container'
    required: true
  open-stack-authorisation-url:
    description: 'URL of OpenStack authorisation end point'
    required: true
  open-stack-project-id:
    description: 'OpenStack project ID with which the target Object Storage container is associated'
    required: true
  swift-client-username:
    description: 'OpenStack / Swift client username for uploads'
    required: true
  swift-client-password:
    description: 'OpenStack / Swift client password for uploads'
    required: true
  swift-region-name:
    description: 'OpenStack / Swift client region name for target Object Storage container'
    required: true
  swift-container-name:
    description: 'OpenStack / Swift client name for target Object Storage container'
    required: true
  private-key:
    description: 'GPG Private key in ascii armor format for signing packages'
    required: true
  private-key-email:
    description: 'GPG Private key email address'
    required: true
  private-key-passphrase:
    description: 'GPG Private key passphrase'
    required: true
  public-key:
    description: 'GPG Public key in ascii armor for verifying signing packages'
    required: true
  list-file-name:
    description: 'Name of the .list file users will download and add to their local machines when consuming your PPA'
    required: true

branding:
  icon: "anchor"
  color: "blue"

runs:
  using: docker
  image: docker://albeego/apt-repository-action:0.0.1